# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allocation_id', models.CharField(db_index=True, max_length=50)),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('employee_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('performed_by', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=core.timezone.now_ist)),
            ],
            options={
                'verbose_name_plural': 'order history',
                'db_table': 'ot_orders_history',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatchAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allocation_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('employee_id', models.CharField(db_index=True, max_length=20)),
                ('employee_name', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.CharField(blank=True, default='', max_length=150)),
                ('client_code', models.CharField(blank=True, default='', max_length=50)),
                ('work_type', models.CharField(blank=True, default='', max_length=100)),
                ('batch', models.CharField(blank=True, default='', max_length=100)),
                ('order_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('completed_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('allocated_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_by', models.CharField(blank=True, default='', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=500)),
                ('sla_notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ot_batch_allocations',
                'ordering': ['-allocated_at'],
                'managed': True,
                'indexes': [models.Index(fields=['employee_id', 'status'], name='ix_alloc_emp_status'), models.Index(fields=['status', 'due_at'], name='ix_alloc_status_due')],
            },
        ),
    ]
