# Generated by Django 5.2.17 on 2026-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('stateabr', models.CharField(blank=True, default='', max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('vendor_rts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eta_rts', models.IntegerField(blank=True, null=True)),
                ('vendor_slt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eta_slt', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=250)),
            ],
            options={
                'db_table': 'ot_order_rates',
                'ordering': ['order_type', 'state', 'county'],
                'managed': True,
            },
        ),
    ]
