# Generated by Django 5.2.17 on 2026-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_orderrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name_plural': 'order history'},
        ),
        migrations.AlterModelOptions(
            name='orderrate',
            options={'managed': False, 'ordering': ['order_type', 'state', 'county']},
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='order_docs/'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='property_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='search_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='vendor_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
