# Generated by Django 5.2.17 on 2026-08-23 05:50

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_sync_state_to_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrate',
            options={'managed': True, 'ordering': ['order_type', 'state', 'county']},
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='allocated_at',
            field=models.DateTimeField(default=core.timezone.now_ist),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='allocated_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        # allocation_id is unique=True, but ot_batch_allocations already holds
        # 255 rows. Adding it unique in one step gives every existing row the
        # same '' default and MySQL rejects the second row with
        # "Duplicate entry '' for key 'allocation_id'".
        #
        # So: add it non-unique, backfill a distinct value per row, then apply
        # the constraint at the end of this migration.
        migrations.AddField(
            model_name='batchallocation',
            name='allocation_id',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='ar_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='chain_sheet',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='chain_sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='completed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='employee_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='report_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='search_package',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='search_package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='sla_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='time_taken',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='allocation_id',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=core.timezone.now_ist),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='from_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='performed_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='to_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='batchallocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('send_for_qc', 'Send for QC'), ('qc_in_progress', 'QC In Progress'), ('completed', 'Completed'), ('dispatch', 'Dispatch'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        # Backfill a distinct allocation_id for the pre-existing rows, then
        # apply the unique constraint. Values are derived from the primary key
        # so they are stable and obviously legacy-generated.
        migrations.RunSQL(
            sql="UPDATE `ot_batch_allocations` SET `allocation_id` = CONCAT('LEGACY-', `id`) "
                "WHERE `allocation_id` = '' OR `allocation_id` IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='batchallocation',
            name='allocation_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
