# Generated by Django 5.2.17 on 2026-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_alter_orderhistory_options_alter_orderrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchallocation',
            name='employee_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='time_taken',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
