# Generated by Django 5.2.17 on 2026-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_batchallocation_employee_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchallocation',
            name='ar_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
