# Generated by Django 5.2.17 on 2026-08-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_batchallocation_ar_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchallocation',
            options={'managed': False, 'ordering': ['-allocated_at']},
        ),
    ]
