# Generated by Django 5.2.17 on 2026-08-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0006_alter_batchallocation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchallocation',
            options={'managed': True, 'ordering': ['-allocated_at']},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name_plural': 'order history'},
        ),
        migrations.AlterModelOptions(
            name='orderrate',
            options={'managed': True, 'ordering': ['order_type', 'state', 'county']},
        ),
    ]
