# Generated by Django 5.2.17 on 2026-08-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0007_alter_batchallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchallocation',
            name='chain_sheet',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='chain_sheet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='report_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='search_package',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='search_package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchallocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('send_for_qc', 'Send for QC'), ('completed', 'Completed'), ('dispatch', 'Dispatch'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
