# Generated by Django 5.2.17 on 2026-08-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0008_batchallocation_chain_sheet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchallocation',
            options={'managed': False, 'ordering': ['-allocated_at']},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name_plural': 'order history'},
        ),
        migrations.AlterModelOptions(
            name='orderrate',
            options={'managed': False, 'ordering': ['order_type', 'state', 'county']},
        ),
    ]
