# Generated by Django 5.2.17 on 2026-08-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0010_alter_batchallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchallocation',
            name='general_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchallocation',
            name='document_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='order_docs/'),
        ),
        migrations.AlterField(
            model_name='batchallocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('send_for_qc', 'Send for QC'), ('qc_in_progress', 'QC In Progress'), ('completed', 'Completed'), ('dispatch', 'Dispatch'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
