# Generated by Django 5.2.17 on 2026-08-25 12:17

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0011_batchallocation_general_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleIndexingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=20)),
                ('project', models.CharField(default='Title Indexing', max_length=150)),
                ('client_code', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=100)),
                ('work_units_completed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
            ],
            options={
                'db_table': 'ot_title_indexing_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
