# Generated by Django 5.2.17 on 2026-08-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0012_titleindexingsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchallocation',
            old_name='time_taken',
            new_name='search_time_taken',
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchallocation',
            name='qc_time_taken',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
