# Generated by Django 5.2.17 on 2026-09-04 07:46

from django.db import migrations, models


def rename_statuses(apps, schema_editor):
    BatchAllocation = apps.get_model('allocations', 'BatchAllocation')
    OrderHistory = apps.get_model('allocations', 'OrderHistory')
    
    # Update BatchAllocation
    BatchAllocation.objects.filter(status='in_progress').update(status='search_in_progress')
    BatchAllocation.objects.filter(status='send_for_qc').update(status='ready_for_qc')
    
    # Update OrderHistory
    OrderHistory.objects.filter(from_status='in_progress').update(from_status='search_in_progress')
    OrderHistory.objects.filter(to_status='in_progress').update(to_status='search_in_progress')
    OrderHistory.objects.filter(from_status='send_for_qc').update(from_status='ready_for_qc')
    OrderHistory.objects.filter(to_status='send_for_qc').update(to_status='ready_for_qc')

def revert_statuses(apps, schema_editor):
    BatchAllocation = apps.get_model('allocations', 'BatchAllocation')
    OrderHistory = apps.get_model('allocations', 'OrderHistory')
    
    BatchAllocation.objects.filter(status='search_in_progress').update(status='in_progress')
    BatchAllocation.objects.filter(status='ready_for_qc').update(status='send_for_qc')
    
    OrderHistory.objects.filter(from_status='search_in_progress').update(from_status='in_progress')
    OrderHistory.objects.filter(to_status='search_in_progress').update(to_status='in_progress')
    OrderHistory.objects.filter(from_status='ready_for_qc').update(from_status='send_for_qc')
    OrderHistory.objects.filter(to_status='ready_for_qc').update(to_status='send_for_qc')

class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0013_rename_time_taken_batchallocation_search_time_taken_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_statuses, revert_statuses),
        migrations.AlterField(
            model_name='batchallocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('search_in_progress', 'Search In Progress'), ('ready_for_qc', 'Ready for QC'), ('qc_in_progress', 'QC In Progress'), ('completed', 'Completed'), ('dispatch', 'Dispatch'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
