# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=20)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('break_type', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(default=core.timezone.now_ist)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, help_text='Seconds taken', null=True)),
                ('allotted_time', models.IntegerField(default=0, help_text='Seconds allowed — set by the server from BREAK_ALLOWANCES')),
                ('is_overrun', models.BooleanField(default=False)),
                ('overrun_notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'aps_Break_Times',
                'ordering': ['-start_time'],
                'managed': True,
                'indexes': [models.Index(fields=['user_id', 'end_time'], name='ix_break_user_open'), models.Index(fields=['start_time'], name='ix_break_start')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('user_id',), name='uq_one_open_break_per_user')],
            },
        ),
    ]
