# Generated by Django 5.2.17 on 2026-08-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0002_sync_state_to_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='breaktime',
            name='is_overrun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breaktime',
            name='overrun_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breaktime',
            name='total_time',
            field=models.FloatField(blank=True, help_text='Seconds taken', null=True),
        ),
        migrations.AddField(
            model_name='breaktime',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
