# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'ot_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], db_index=True, default='employee', max_length=20)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.CharField(blank=True, default='', max_length=150)),
                ('shift', models.CharField(blank=True, default='', max_length=50)),
                ('reporting_to', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_employees',
                'ordering': ['name'],
                'managed': True,
                'indexes': [models.Index(fields=['role', 'status'], name='ix_emp_role_status'), models.Index(fields=['project'], name='ix_emp_project')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('login_time', models.DateTimeField(default=core.timezone.now_ist)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'login history',
                'db_table': 'ot_user_login_history',
                'ordering': ['-login_time'],
                'managed': True,
                'indexes': [models.Index(fields=['emp_id', 'date'], name='ix_login_emp_date'), models.Index(fields=['logout_time'], name='ix_login_open')],
            },
        ),
    ]
