# Generated by Django 5.2.17 on 2026-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active_inactive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='client_code',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, db_column='joining_date', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, db_column='work_location', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.CharField(blank=True, db_column='projects', default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(blank=True, db_column='shift_time', default='', max_length=50),
        ),
    ]
