# Generated by Django 5.2.17 on 2026-08-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_active_inactive_date_employee_client_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'managed': False, 'ordering': ['-login_time'], 'verbose_name_plural': 'login history'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
