# Generated by Django 5.2.17 on 2026-08-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_employee_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'managed': True, 'ordering': ['-login_time'], 'verbose_name_plural': 'login history'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
