# Generated by Django 5.2.17 on 2026-08-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employee_options_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alternate_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('project_admin', 'Project Admin'), ('team_lead', 'Team Lead'), ('employee', 'Employee')], db_index=True, default='employee', max_length=20),
        ),
    ]
