# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceState',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('on_break', 'On break'), ('working', 'Working'), ('busy', 'Busy'), ('online', 'Online'), ('idle', 'Idle'), ('offline', 'Offline')], db_index=True, default='offline', max_length=10)),
                ('status_source', models.CharField(choices=[('socket', 'Socket'), ('work_session', 'Work session'), ('break', 'Break'), ('manual', 'Manual')], default='socket', max_length=15)),
                ('custom_status', models.CharField(blank=True, default='', max_length=80)),
                ('connection_count', models.SmallIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=core.timezone.now_ist)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_presence',
                'ordering': ['emp_id'],
                'indexes': [models.Index(fields=['status', 'last_seen_at'], name='ix_presence_status')],
            },
        ),
    ]
