# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCode',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(blank=True, default='', max_length=150)),
                ('project', models.CharField(blank=True, db_index=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'ot_clientcode',
                'ordering': ['client_code'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=150, unique=True)),
                ('project_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('client_name', models.CharField(blank=True, default='', max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ot_projects',
                'ordering': ['project_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ot_shift_master',
                'ordering': ['start_time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_type', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('standard_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'work type',
                'db_table': 'ot_worktypes',
                'ordering': ['work_type'],
                'managed': True,
            },
        ),
    ]
