# Generated by Django 5.2.17 on 2026-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcode',
            name='cc_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientcode',
            name='worktypes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='client_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='worktypes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='worktype',
            name='wt_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
