# Generated by Django 5.2.17 on 2026-08-23 05:50

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_sync_state_to_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcode',
            options={'managed': True, 'ordering': ['cc_id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'ordering': ['project_id']},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'managed': True, 'ordering': ['wt_id'], 'verbose_name': 'work type'},
        ),
        migrations.AddField(
            model_name='clientcode',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='clientcode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='clientcode',
            name='project',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_at',
            field=models.DateTimeField(default=core.timezone.now_ist),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(default=core.timezone.now_ist),
        ),
        migrations.AddField(
            model_name='worktype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='worktype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='standard_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='work_type',
            # unique=True on a table with 58 existing rows: adding it unique in
            # one step gives every row the same '' default and MySQL rejects the
            # second with "Duplicate entry '' for key 'work_type'". Added
            # non-unique here; backfilled and made unique at the end.
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        # ot_worktypes already holds these values under the legacy column name
        # `worktypename` (58 rows, all distinct, longest 52 chars). Copying them
        # across both satisfies the unique constraint and carries the real data
        # into the column the model reads -- rather than leaving 58 blanks.
        migrations.RunSQL(
            sql="UPDATE `ot_worktypes` SET `work_type` = `worktypename` "
                "WHERE (`work_type` = '' OR `work_type` IS NULL) AND `worktypename` IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
