# Generated by Django 5.2.17 on 2026-08-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_clientcode_cc_id_clientcode_worktypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcode',
            options={'managed': False, 'ordering': ['client_code']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False, 'ordering': ['project_name']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'managed': False, 'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'managed': False, 'ordering': ['work_type'], 'verbose_name': 'work type'},
        ),
    ]
