# Generated by Django 5.2.17 on 2026-08-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_clientcode_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcode',
            options={'managed': True, 'ordering': ['cc_id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True, 'ordering': ['project_id']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'managed': True, 'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'managed': True, 'ordering': ['wt_id'], 'verbose_name': 'work type'},
        ),
    ]
