# Generated by Django 5.2.17 on 2026-08-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_clientcode_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(db_column='endedAt'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(db_column='shift', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(db_column='startedAt'),
        ),
    ]
