# Generated by Django 5.2.17 on 2026-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_alter_shift_end_time_alter_shift_shift_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_simplified_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
