# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('integer', 'Number'), ('boolean', 'Yes/No'), ('json', 'JSON')], default='string', max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, db_index=True, default='general', max_length=50)),
                ('is_editable', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_app_settings',
                'ordering': ['category', 'key'],
                'managed': True,
            },
        ),
    ]
