# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, help_text='Who the feedback is about', max_length=20)),
                ('emp_name', models.CharField(blank=True, default='', max_length=100)),
                ('feedback_type', models.CharField(choices=[('quality', 'Quality'), ('audit', 'Audit'), ('coaching', 'Coaching'), ('appreciation', 'Appreciation')], default='quality', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='info', max_length=10)),
                ('project', models.CharField(blank=True, default='', max_length=150)),
                ('order_batch_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('work_type', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('error_count', models.IntegerField(default=0)),
                ('sample_size', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(db_index=True, default=core.timezone.now_ist)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'db_table': 'ot_feedbacks',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['emp_id', 'created_at'], name='ix_fb_emp_created'), models.Index(fields=['order_batch_id'], name='ix_fb_batch')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('feedback', models.ForeignKey(db_column='feedback_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedback.feedback')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_images', to='files.storedfile')),
            ],
            options={
                'db_table': 'ot_feedback_images',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
