# Generated by Django 5.2.17 on 2026-08-13 05:27

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='acknowledgment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='acknowledgment_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='action_taken',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='client_code',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='feedback',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_provided_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_received_mode',
            field=models.CharField(blank=True, default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_recorded',
            field=models.CharField(blank=True, default='internalAudit', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='processed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=core.timezone.now_ist, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=core.timezone.now_ist, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='emp_id',
            field=models.CharField(db_index=True, help_text='Who the feedback is about', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='error_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('quality', 'Quality'), ('audit', 'Audit'), ('coaching', 'Coaching'), ('appreciation', 'Appreciation')], default='quality', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='order_batch_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sample_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='severity',
            field=models.CharField(blank=True, choices=[('info', 'Informational'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='work_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
