# Generated by Django 5.2.17 on 2026-08-23 05:50

import core.timezone
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_sync_state_to_production'),
        ('files', '0001_initial'),
    ]

    operations = [
        # work_type and created_by are altered through a transient NOT NULL
        # step, and both hold NULLs on live rows (430 and 863 in production).
        # Under STRICT_TRANS_TABLES that ALTER fails outright, so backfill
        # first. '' is each field's own declared default
        # (CharField(blank=True, default="")), so no meaning is invented.
        migrations.RunSQL(
            sql=(
                "UPDATE `ot_feedbacks` SET `work_type` = '' WHERE `work_type` IS NULL;"
                "UPDATE `ot_feedbacks` SET `created_by` = '' WHERE `created_by` IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='feedback',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='error_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('quality', 'Quality'), ('audit', 'Audit'), ('coaching', 'Coaching'), ('appreciation', 'Appreciation')], default='quality', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sample_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_images', to='files.storedfile'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=core.timezone.now_ist, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='emp_id',
            field=models.CharField(db_index=True, help_text='Who the feedback is about', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='order_batch_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='severity',
            field=models.CharField(blank=True, choices=[('info', 'Informational'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='work_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
