# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20)),
                ('project', models.CharField(blank=True, default='', max_length=150)),
                ('work_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_date', models.DateField(db_index=True)),
                ('target_units', models.IntegerField(default=0)),
                ('achieved_units', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_targets',
                'ordering': ['-target_date'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'project', 'work_type', 'target_date'), name='uq_target_emp_day')],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.CharField(blank=True, default='', max_length=150)),
                ('client_code', models.CharField(blank=True, default='', max_length=50)),
                ('work_type', models.CharField(blank=True, default='', max_length=100)),
                ('batch', models.CharField(blank=True, default='', max_length=100)),
                ('work_units', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=core.timezone.now_ist)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.FloatField(blank=True, help_text='Seconds, excluding pauses', null=True)),
                ('average_time', models.FloatField(blank=True, help_text='Seconds per work unit', null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_by', models.CharField(blank=True, default='', max_length=20)),
                ('paused_elapsed', models.FloatField(default=0, help_text='Total seconds spent paused')),
                ('allocation_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_started', models.SmallIntegerField(choices=[(0, 'Allocated'), (1, 'Running'), (2, 'Completed')], db_index=True, default=0)),
                ('review', models.CharField(blank=True, default='', max_length=255)),
                ('pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ot_user_work_data',
                'ordering': ['-start_time'],
                'managed': True,
                'indexes': [models.Index(fields=['emp_id', 'start_time'], name='ix_work_emp_start'), models.Index(fields=['is_started', 'start_time'], name='ix_work_started'), models.Index(fields=['project', 'start_time'], name='ix_work_project')],
            },
        ),
    ]
