# Generated by Django 5.2.17 on 2026-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True), ('is_started', 1)), fields=('emp_id',), name='uq_one_open_session_per_emp'),
        ),
    ]
