# Generated by Django 5.2.17 on 2026-08-23 05:50

import core.timezone
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_sync_state_to_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='target',
            name='achieved_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='created_at',
            field=models.DateTimeField(default=core.timezone.now_ist),
        ),
        migrations.AddField(
            model_name='target',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='target',
            name='emp_id',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='target',
            name='target_date',
            # Sentinel for the 4 pre-existing ot_targets rows. A DateField cannot
            # take '' as a one-off default; MySQL rejects it outright.
            field=models.DateField(db_index=True, default=datetime.date(1970, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='target_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='work_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True), ('is_started', 1)), fields=('emp_id',), name='uq_one_open_session_per_emp'),
        ),
    ]
