# Generated by Django 5.2.17 on 2026-08-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0006_alter_batchallocation_options'),
        ('tracking', '0002_worksession_uq_one_open_session_per_emp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'managed': False, 'ordering': ['-target_date']},
        ),
        migrations.AlterModelOptions(
            name='worksession',
            options={'managed': False, 'ordering': ['-start_time']},
        ),
        migrations.CreateModel(
            name='EmployeeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_sheet', models.FileField(blank=True, null=True, upload_to='submissions/chain_sheets/')),
                ('search_package', models.FileField(blank=True, null=True, upload_to='submissions/search_packages/')),
                ('report', models.FileField(blank=True, null=True, upload_to='submissions/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(db_column='allocation_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='allocations.batchallocation', to_field='allocation_id')),
            ],
            options={
                'db_table': 'ot_employee_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
