# Generated by Django 5.2.17 on 2026-08-13 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_target_options_alter_worksession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'managed': True, 'ordering': ['-target_date']},
        ),
        migrations.AlterModelOptions(
            name='worksession',
            options={'managed': True, 'ordering': ['-start_time']},
        ),
    ]
