# Generated by Django 5.2.17 on 2026-08-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_target_options_alter_worksession_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='average_time',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='work_units',
        ),
    ]
