# Generated by Django 5.2.17 on 2026-08-28 06:08

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_worksession_average_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=20)),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('total_break_time', models.FloatField(default=0.0, help_text='Total break seconds')),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_attendance',
                'ordering': ['-date'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'date'), name='uq_attendance_emp_day')],
            },
        ),
    ]
