# Generated by Django 5.2.17 on 2026-09-03 05:34

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('total_time', models.CharField(default='00:00:00', max_length=20)),
                ('project_name', models.CharField(default='SOFTWARE', max_length=150)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('updated_at', models.DateTimeField(default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_software_shifts',
                'ordering': ['-date', '-created_at'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'date'), name='uq_software_shift_emp_day')],
            },
        ),
    ]
