# Generated by Django 5.2.17 on 2026-09-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_softwareshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareshift',
            name='accumulated_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='softwareshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareshift',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwareshift',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='softwareshift',
            name='pause_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='softwareshift',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
