# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requested_by', models.CharField(db_index=True, max_length=20)),
                ('report_key', models.CharField(max_length=60)),
                ('params', models.JSONField(default=dict)),
                ('export_format', models.CharField(default='xlsx', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(db_index=True, default=core.timezone.now_ist)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to='files.storedfile')),
            ],
            options={
                'db_table': 'ot_report_jobs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['requested_by', '-id'], name='ix_reportjob_user')],
            },
        ),
    ]
