# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketTicket',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=core.timezone.now_ist)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ot_ws_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=80)),
                ('audience', models.CharField(max_length=80)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_realtime_outbox',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['topic', 'id'], name='ix_outbox_topic_id')],
            },
        ),
    ]
