# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner_emp_id', models.CharField(db_index=True, max_length=20)),
                ('context', models.CharField(choices=[('feedback', 'Feedback image'), ('allocation', 'Allocation import'), ('export', 'Report export'), ('chat', 'Chat attachment'), ('misc', 'Other')], default='misc', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('stored_path', models.CharField(help_text='Relative to PRIVATE_STORAGE_ROOT', max_length=500)),
                ('thumb_path', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=core.timezone.now_ist)),
            ],
            options={
                'db_table': 'ot_stored_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_emp_id', 'context'], name='ix_file_owner_ctx')],
            },
        ),
    ]
