# Generated by Django 5.2.17 on 2026-08-05 11:58

import core.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_emp_id', models.CharField(db_index=True, max_length=20)),
                ('notif_type', models.CharField(db_index=True, max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('link_url', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('actor_emp_id', models.CharField(blank=True, default='', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=core.timezone.now_ist)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'ot_notifications',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['recipient_emp_id', 'read_at', '-id'], name='ix_notif_inbox')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_index=True, max_length=20)),
                ('notif_type', models.CharField(max_length=60)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ot_notification_prefs',
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'notif_type'), name='uq_notif_pref')],
            },
        ),
    ]
